text:
    fontSize: 11
    lineHeight: 1.2
    listLineHeight: 1
    listMarker: '-'
    figureText: Figure
page:
    marginTop: 20
    marginBottom: 20
    marginHori: 15
    columnGap: 7
    columns: 2
    pageNumbers: true
    startPageNumber: 1
toc:
    enabled: true
    lineHeight: 1.3
    fontSize: 12
    heading: Table of Contents
tof:
    enabled: true
    lineHeight: 1.3
    fontSize: 12
    heading: Table of Figures
margins:
    paragraph: 1
    heading_top: 3
    heading_bottom: 1
    list: 1
    image: 4
    code: 2
paper:
    title: turbocommit
    authors: Raik Rohde 4380676
    debug: false
citation:
    enabled: true
    file: bib.json
    heading: References
    bibFontSize: 12
    bibLineHeight: 1.4
    csl: chicago-author-date.csl
    locale: ""
code:
    style: dracula
    fontSize: 10
    characterSpacing: -0.75
    lineNumbers: true
    dot: true
table:
    padding: 1.5
cover:
    enabled: true
    subtitle: A Case Study in Applying Al to Streamline the Software Development Process
    abstract: Conventional commit messages play a vital role in maintaining a clear and well-structured version control history in software development. However, writing informative and consistent commit messages can be challenging and time-consuming for developers. This paper presents `turbocommit`, a novel tool that leverages the power of AI to generate conventional commit messages from git diffs. Utilizing the GPT-3.5 Turbo language model, `turbocommit` aims to streamline the software development process by automating commit message creation and ensuring compliance with the Conventional Commits specification. The paper delves into the development process, including requirement analysis, implementation, and evaluation of the tool. We compare the performance of AI-generated commit messages with manually written ones in terms of accuracy, readability, and adherence to the specification.
