text:
    fontSize: 11
    lineHeight: 1.2
    listLineHeight: 1
    listMarker: '-'
    figureText: Figure
page:
    marginTop: 20
    marginBottom: 20
    marginHori: 15
    columnGap: 7
    columns: 2
    pageNumbers: true
    startPageNumber: 1
toc:
    enabled: true
    lineHeight: 1.3
    fontSize: 12
    heading: Table of Contents
tof:
    enabled: true
    lineHeight: 1.3
    fontSize: 12
    heading: Table of Figures
margins:
    paragraph: 1
    heading_top: 3
    heading_bottom: 1
    list: 1
    image: 4
    code: 2
paper:
    title: turbocommit
    authors: Raik Rohde 4380676, Atos Information GmbH
    debug: false
citation:
    enabled: true
    file: bib.json
    heading: References
    bibFontSize: 12
    bibLineHeight: 1.4
    csl: chicago-author-date.csl
    locale: ""
code:
    style: dracula
    fontSize: 10
    characterSpacing: -0.75
    lineNumbers: true
    dot: true
table:
    padding: 1.5
cover:
    enabled: true
    subtitle: A Case Study in Applying Al to Streamline the Software Development Process
